-- Add new fields to users table
ALTER TABLE users ADD COLUMN IF NOT EXISTS age INTEGER;
ALTER TABLE users ADD COLUMN IF NOT EXISTS location VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS height VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS size VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS admin_comments TEXT;

